# -*- coding: utf-8 -*-
"""seaborn

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1i6hHLrW798mKPdvCs-4GLZak70GTwfvi

Distribution Plot
"""

# this are created for quantitative variable
# 1.histplot
# 2.jointplot
# 3.pairplot
# 4.runplot
import seaborn as sns
import matplotlib.pyplot as plt

#datasets
df = sns.load_dataset('tips')
df

df['size'].unique()

sns.displot(df['total_bill'])

#histogram is type of plot which is best resprest distribution of data
#show curnal density astimatter
plt.subplot(1,2,1)
sns.displot(df['total_bill'],bins = 20,kde = True)
plt.subplot(1,2,2)
sns.displot(df['tip'],bins = 20,kde = True)

sns.jointplot(x = "total_bill", y = "tip" , data =df,kind="scatter")

sns.jointplot(x = "total_bill", y = "tip" , data =df,kind="hex")

sns.jointplot(x = "total_bill", y = "tip" , data =df,kind="kde")

sns.jointplot(x = "total_bill", y = "tip" , data =df,kind="reg")

"""Pair ploat"""

sns.pairplot(df,hue="sex")
#hue is for differnciate

sns.pairplot(df,hue="size",palette="husl")
# palette used for coluring in specific way

"""RUG PLOT"""

sns.rugplot(df['total_bill'])

